services:
  db:
    image: postgres
    env_file:
      - .env
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - 5432:5432
    volumes:
      - urlshortenervolume:/var/lib/postgresql/data

volumes:
  urlshortenervolume:
