services:
  db:
    image: postgres
    env_file:
      - .env
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - 5432:5432
    volumes:
      - urlshortenervolume:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  celery_worker:
    build: .
    depends_on:
      - redis
      - db
    command: /bin/sh -c "./scripts/entrypoint.sh && cd backend && poetry run celery -A worker.celery_app worker"
    volumes:
      - .:/backend
  backend:
    depends_on:
      - db
    build: .
    command: /bin/sh -c "./scripts/entrypoint.sh && cd backend && poetry run uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - 127.0.0.1:8000:8000
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend

volumes:
  urlshortenervolume:
