"""Add UrlMapping table

Revision ID: 3975f1325759
Revises:
Create Date: 2024-10-20 14:21:00.027535

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3975f1325759"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urlmapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("short_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_access", sa.DateTime(), nullable=True),
        sa.Column("click_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_urlmapping_original_url"), "urlmapping", ["original_url"], unique=False
    )
    op.create_index(
        op.f("ix_urlmapping_short_url"), "urlmapping", ["short_url"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urlmapping_short_url"), table_name="urlmapping")
    op.drop_index(op.f("ix_urlmapping_original_url"), table_name="urlmapping")
    op.drop_table("urlmapping")
    # ### end Alembic commands ###
